version: "3"

services:
  tests:
    working_dir: /opt/code
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/code/
    command: pytest test/
    environment:
      SERVICE_NAME: tests
    depends_on:
      - producer
      - image_processor
      - stats_reporter
